package com.example.labassignment.database

import com.example.labassignment.model.*
import com.example.labassignment.model.Movie


object MovieDB {
    val movies = listOf(
        Movie(
            adult = false,
            backdrop_path = "/op3qmNhvwEvyT7UFyPbIfQmKriB.jpg",
            budget = 55000000,
            genres = listOf(Genre(14,"Fantasy"), Genre(12,"Adventure"), Genre(28,"Action")),
            homepage = "https://inthelostlands.com",
            id = 324544,
            imdb_id = "tt4419684",
            original_language = "en",
            original_title = "In the Lost Lands",
            overview = "A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where the sorceress and her guide, the drifter Boyce must outwit and outfight man and demon.",
            popularity = 727.9871,
            poster_path = "/iHf6bXPghWB6gT8kFkL1zo00x6X.jpg",
            production_companies = listOf(
                ProductionCompany( 47, "/i7Z9ot2o3N5Sa3HrF09kniFs2y8.png", "Constantin Film", "DE"),
                ProductionCompany( 187303, "/5CJA1Ej3gJxosjkzz2T7AeLw1SQ.png", "Spark Productions", "CH")),
            production_countries = listOf(
                ProductionCountry("DE", "Germany"),
                ProductionCountry("CH", "Switzerland")),
            release_date = "2025-02-27",
            revenue = 4755330,
            runtime = 102,
            spoken_languages = listOf(
                SpokenLanguage("German", "de", "Deutsch"), SpokenLanguage("English", "en", "English")
            ),
            status = "Released",
            tagline = "She seeks the power to free her people.",
            title =  "In the Lost Lands",
            video = false,
            vote_average = 6.294,
            vote_count = 170,
        ),
        Movie(
            adult = false,
            backdrop_path = "/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
            budget = 150000000,
            genres = listOf(Genre(10751, "Family"), Genre(35, "Comedy"),Genre(14,"Fantasy"), Genre(12,"Adventure")),
            homepage = "https://www.minecraft-movie.com",
            id = 950387,
            imdb_id = "tt3566834",
            original_language = "en",
            original_title = "A Minecraft Movie",
            overview = "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
            popularity = 673.4901,
            poster_path = "/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
            production_companies = listOf(
                ProductionCompany( 174, "/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png", "Warner Bros. Pictures", "US"),
                ProductionCompany(923, "/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png", "Legendary Pictures", "US"),
                ProductionCompany(110691, "/i0D9b0veZbValgEFiJjSd0mbb9C.png", "Mojang Studios", "SE"),
                ProductionCompany(829, "/aXqwCvJSCDbTclkxAYfsT1l4Dsa.png", "Vertigo Entertainment", "US"),
                ProductionCompany(  159602, "/e3KodIPxOSC6xpzgIBISB4COQcu.png", "On the Roam", "US"),
                ProductionCompany(216687, "/kKVYqekveOvLK1IgqdJojLjQvtu.png", "Domain Entertainment", "US")),
            production_countries = listOf(ProductionCountry("SE", "Sweden"),
                ProductionCountry("US", "United States of America")),
            release_date = "2025-03-31",
            revenue = 552664857,
            runtime = 101,
            spoken_languages = listOf(SpokenLanguage("English", "en", "English")),
            status = "Released",
            tagline = "Be there and be square.",
            title = "A Minecraft Movie",
            video = false,
            vote_average = 6.902,
            vote_count = 547
        ),
        Movie(
            adult = false,
            backdrop_path =  "/k32XKMjmXMGeydykD32jfER3BVI.jpg",
            budget = 0,
            genres = listOf(Genre(28, "Action"), Genre(9648, "Mystery"),Genre(18,"Drama")),
            homepage = "https://www.amazon.com/dp/B0DV3V4HH6",
            id = 1045938,
            imdb_id = "tt23476986",
            original_language = "en",
            original_title = "G20",
            overview = "After the G20 Summit is overtaken by terrorists, President Danielle Sutton must bring all her statecraft and military experience to defend her family and her fellow leaders.",
            popularity = 687.7088,
            poster_path = "/tSee9gbGLfqwvjoWoCQgRZ4Sfky.jpg",
            production_companies = listOf(
                ProductionCompany( 64469, "/1hhdZwxGJDvFDArF8VDiqtdorSq.png", "JuVee Productions", "US"),
                ProductionCompany( 1757,"/fc9qw5GoTbyWGa0QcfbsZFzuMKQ.png","Mad Chance","US"),
                ProductionCompany(2531,"/9MfCJ2G6Nrf9yyRj4tAgPmMiDcn.png","MRC","US"),
                ProductionCompany(210099,"/d6HwljzlOzxJ4tXlrpRkNZaZMWL.png","Amazon MGM Studios","US")),
            production_countries = listOf(ProductionCountry("US", "United States of America")),
            release_date = "2025-04-09",
            revenue = 0,
            runtime = 110,
            spoken_languages = listOf(SpokenLanguage("English", "en", "English")),
            status = "Released",
            tagline = "Never underestimate a patriot",
            title = "G20",
            video = false,
            vote_average = 6.538,
            vote_count = 213
        ),
        Movie(
            adult = false,
            backdrop_path = "/sNx1A3822kEbqeUxvo5A08o4N7o.jpg",
            budget = 18000000,
            genres = listOf(Genre(28, "Action"), Genre(35, "Comedy"),Genre(53,"Thriller")),
            homepage = "https://www.novocainemovie.com",
            id = 1195506,
            imdb_id = "tt29603959",
            original_language = "en",
            original_title = "Novocaine",
            overview = "When the girl of his dreams is kidnapped, everyman Nate turns his inability to feel pain into an unexpected strength in his fight to get her back.",
            popularity = 551.0521,
            poster_path = "/xmMHGz9dVRaMY6rRAlEX4W0Wdhm.jpg",
            production_companies = listOf(
                ProductionCompany(23921, "/simDvqT8y6jhP530ggUMbikvVKc.png", "Circle of Confusion", "US"),
                ProductionCompany(25577,"/2trboP7Exx3LEQqSHoo1sAmsC1i.png","Safehouse Pictures","US"),
                ProductionCompany(4,"/gz66EfNoYPqHTYI4q9UEN4CbHRc.png","Paramount Pictures","US"),
                ProductionCompany( 247121,null,"Infrared Pictures","US"),
                ProductionCompany(216687,"/kKVYqekveOvLK1IgqdJojLjQvtu.png","Domain Entertainment","US"),
                ProductionCompany(7493,"/fHitYiGUCkRafgt6VPYQlXWLkdp.png","FilmNation Entertainment","US"),
                ProductionCompany(257516,null,"Mediaflix","")),
            production_countries = listOf(ProductionCountry("US", "United States of America")),
            release_date = "2025-03-12",
            revenue = 33561854,
            runtime = 110,
            spoken_languages = listOf(SpokenLanguage("English", "en", "English")),
            status = "Released",
            tagline = "Nathan Caine can't feel pain.",
            title = "Novocaine",
            video = false,
            vote_average = 6.861,
            vote_count = 427
        ),
        Movie(
            adult = false,
            backdrop_path = "/ce3prrjh9ZehEl5JinNqr4jIeaB.jpg",
            budget = 180000000,
            genres = listOf(Genre(28, "Action"), Genre(878, "Science Fiction"),Genre(53,"Thriller")),
            homepage = "https://www.marvel.com/movies/captain-america-brave-new-world",
            id = 822119,
            imdb_id = "tt14513804",
            original_language = "en",
            original_title = "Captain America: Brave New World",
            overview = "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
            popularity = 360.3738,
            poster_path = "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
            production_companies = listOf(
                ProductionCompany(420,"/hUzeosd33nzE5MCNsZxCGEKTXaQ.png", "Marvel Studios", "US"),
                ProductionCompany(176762,null,"Kevin Feige Productions","US")),
            production_countries = listOf(ProductionCountry("US", "United States of America")),
            release_date = "2025-02-12",
            revenue = 411409721,
            runtime = 119,
            spoken_languages = listOf(SpokenLanguage("English", "en", "English"),
                SpokenLanguage("Japanese", "ja", "日本語"),
                SpokenLanguage("Spanish","es","Español")),
            status = "Released",
            tagline = "The future favors the brave.",
            title = "Captain America: Brave New World",
            video = false,
            vote_average = 6.14,
            vote_count = 1374
        )
        // Add more movies accordingly
    )
}

